version: '2'
services:
  haproxy:
    hostname: HAPROXY
    container_name: ry-haproxy
    build:
      context: haproxy
      dockerfile: Dockerfile
      args:
       - V2RAY_PORT=${V2RAY_PORT}
       - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "80:80"
      - "443:443"
      - "${V2RAY_PORT}:${V2RAY_PORT}"
    networks:
      intnet:
        ipv4_address: 10.10.11.2
    restart: on-failure

  ry-v2ray:
    hostname: V2RAY
    container_name: ry-v2ray
    build:
      context: ry-v2ray
      dockerfile: Dockerfile
      args:
        - V2RAY_PORT=${V2RAY_PORT}
        - V2RAY_UUID=${V2RAY_UUID}
    volumes:
        - ./log/:/var/log/v2ray
    networks:
      intnet:
        ipv4_address: 10.10.11.3
    restart: on-failure
    depends_on:
      - haproxy

  nginx:
    hostname: NGINX
    container_name: ry-nginx
    build:
      context: nginx
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    networks:
      intnet:
        ipv4_address: 10.10.11.4
    restart: on-failure
    depends_on:
      - haproxy

networks:
  intnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.11.0/24
          gateway: 10.10.11.1
