version: '2'
services:
  ry-v2ray:
    hostname: V2RAY
    container_name: ry-v2ray
    build:
      context: ry-v2ray
      dockerfile: Dockerfile
      args:
        - V2RAY_PORT=${V2RAY_PORT}
        - V2RAY_UUID=${V2RAY_UUID}
    volumes:
        - ./log/:/var/log/v2ray
    ports:
      - "${V2RAY_PORT}:${V2RAY_PORT}"

  nginx:
    hostname: NGINX
    container_name: ry-nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: on-failure
