version: '2'
services:
  caddy:
    hostname: CADDY
    container_name: ry-caddy
    build:
      context: caddy
      dockerfile: Dockerfile
      args:
       - V2RAY_PORT=${V2RAY_PORT}
       - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - ./caddy/html/:/usr/share/caddy
    networks:
      intnet:
        ipv4_address: 10.10.11.2
    restart: on-failure

  ry-v2ray:
    hostname: V2RAY
    container_name: ry-v2ray
    build:
      context: v2ray
      dockerfile: Dockerfile
      args:
        - V2RAY_PORT=${V2RAY_PORT}
        - V2RAY_UUID=${V2RAY_UUID}
        - V2RAY_ALTERID=${V2RAY_ALTERID}
    volumes:
        - ./log/:/var/log/v2ray
    networks:
      intnet:
        ipv4_address: 10.10.11.3
    restart: on-failure
    depends_on:
      - caddy

networks:
  intnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.11.0/24
          gateway: 10.10.11.1
